### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aike** [aike/TSSCCjs#1]
- [x] #MML directive support
- [x] hang up
- [x] parse error recovery
- [x] add normal MML command parse test
- [x] multi line comment support
- [ ] atcp extended MML support
- [ ] all note off
